apiVersion: v1
kind: ConfigMap
data:
  USERS_TODO_TABLE: Users-Todo-dev
  USERID_INDEX: UserIdIndex
  TODOS_S3_BUCKET: kubernetes-sing-todos-dev
  THUMBNAILS_S3_BUCKET: kubernetes-todos-sing-thumbnail-dev
  SIGNED_URL_EXPIRATION: "300"
  AWS_REGION: us-east-2
  AWS_PROFILE: default
  TODO_VERSION: v1
  URL: http://localhost:3000  
metadata:
  name: env-config
